### ISSUE TITLE
Can you specify the fonts for this rice?

### ISSUE THREAD

**Issue by ghost** [TheCactusBlue/dotfiles#2]
this is not an issue, is more like a recommendation, i really like the work you do in this rice and i want to use it in my workstation, but i can't figure out which fonts you use

**Comment by TheCactusBlue** [comment]
[Fira Code with NerdFont patches.](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode)

**Comment by ghost** [comment]
> [Fira Code with NerdFont patches.](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode)

thanks
